### ISSUE TITLE
unexpected token `newline'

### ISSUE THREAD

**Issue by Karter315** [thamarnan/remarkable-custom-template-refresh#2]
Hi and thanks for the guidance. I followed the step but received the following error when I ran the script.
Version 1.6.0.6

> ./refresh_template.sh: line 7: syntax error near unexpected token `newline'
> ./refresh_template.sh: line 7: `<!DOCTYPE html>'

**Comment by mdglawson** [comment]
Hi, I'm not the author, only another user, but I think you may be loading the wrong file.  If you've done the equivalent of right hand clicking and downloading the SH file you'll get a very different file (c.72k) to if you download the zip, unzip it and then look at the SH file (c.3k).  You can check them both with an editor like Notepad++.

If that's what you've done, you'll see an error like the one you describe (I know, I've done it), since you're loading an HTML file dressed up as a SH file, not the correct SH file.

**Comment by Karter315** [comment]
That's exactly what I did!!! Brother, thanks for the guidance, I love my tablet even more now, due to your assistance.

**Comment by thamarnan** [comment]
TY
